// MatAIme: reference data — all 118 known elements, molecules, and alloys.

const ELEMENTS = {
  H: { z:1, name:"Hydrogen", shells:[1], category:"nonmetal", mass:1.008, stableWeight:true, melt:-259, boil:-253, density:0.08988, densityUnit:"g/L", phase:"Gas", en:2.2, theoretical:false, blurb:"The simplest and most abundant element in the universe — one proton, one electron, no neutrons in its common form." },
  He: { z:2, name:"Helium", shells:[2], category:"noble-gas", mass:4.003, stableWeight:true, melt:-272, boil:-269, density:0.1786, densityUnit:"g/L", phase:"Gas", en:null, theoretical:false, blurb:"Second most abundant element in the universe; mined from natural gas." },
  Li: { z:3, name:"Lithium", shells:[2,1], category:"alkali", mass:6.94, stableWeight:true, melt:180, boil:1330, density:0.534, densityUnit:"g/cm³", phase:"Solid", en:0.98, theoretical:false, blurb:"Lightest metal that exists; key to modern rechargeable batteries." },
  Be: { z:4, name:"Beryllium", shells:[2,2], category:"alkaline-earth", mass:9.012, stableWeight:true, melt:1287, boil:2469, density:1.85, densityUnit:"g/cm³", phase:"Solid", en:1.57, theoretical:false, blurb:"A light, stiff, toxic metal used in aerospace and X-ray windows." },
  B: { z:5, name:"Boron", shells:[2,3], category:"metalloid", mass:10.81, stableWeight:true, melt:2076, boil:3927, density:2.08, densityUnit:"g/cm³", phase:"Solid", en:2.04, theoretical:false, blurb:"Used in borosilicate glass (Pyrex) and as a plant nutrient." },
  C: { z:6, name:"Carbon", shells:[2,4], category:"nonmetal", mass:12.011, stableWeight:true, melt:null, boil:null, density:2.267, densityUnit:"g/cm³", phase:"Solid", en:2.55, theoretical:false, blurb:"Backbone of life; forms diamond, graphite, and graphene." },
  N: { z:7, name:"Nitrogen", shells:[2,5], category:"nonmetal", mass:14.007, stableWeight:true, melt:-210, boil:-196, density:1.251, densityUnit:"g/L", phase:"Gas", en:3.04, theoretical:false, blurb:"Makes up 78% of the air; essential to amino acids and DNA." },
  O: { z:8, name:"Oxygen", shells:[2,6], category:"nonmetal", mass:15.999, stableWeight:true, melt:-219, boil:-183, density:1.429, densityUnit:"g/L", phase:"Gas", en:3.44, theoretical:false, blurb:"Essential for life; most abundant element in Earth's crust." },
  F: { z:9, name:"Fluorine", shells:[2,7], category:"halogen", mass:18.998, stableWeight:true, melt:-220, boil:-188, density:1.696, densityUnit:"g/L", phase:"Gas", en:3.98, theoretical:false, blurb:"Most reactive nonmetal; used in toothpaste to strengthen enamel." },
  Ne: { z:10, name:"Neon", shells:[2,8], category:"noble-gas", mass:20.18, stableWeight:true, melt:-249, boil:-246, density:0.9002, densityUnit:"g/L", phase:"Gas", en:null, theoretical:false, blurb:"Glows reddish-orange when electrified; the original neon sign gas." },
  Na: { z:11, name:"Sodium", shells:[2,8,1], category:"alkali", mass:22.99, stableWeight:true, melt:98, boil:883, density:0.968, densityUnit:"g/cm³", phase:"Solid", en:0.93, theoretical:false, blurb:"Explosively reactive metal; bonds with chlorine to form table salt." },
  Mg: { z:12, name:"Magnesium", shells:[2,8,2], category:"alkaline-earth", mass:24.305, stableWeight:true, melt:650, boil:1090, density:1.738, densityUnit:"g/cm³", phase:"Solid", en:1.31, theoretical:false, blurb:"Burns with white light; center of chlorophyll molecules in plants." },
  Al: { z:13, name:"Aluminium", shells:[2,8,3], category:"post-metal", mass:26.982, stableWeight:true, melt:660, boil:2470, density:2.7, densityUnit:"g/cm³", phase:"Solid", en:1.61, theoretical:false, blurb:"Endlessly recyclable, light, and corrosion-resistant metal." },
  Si: { z:14, name:"Silicon", shells:[2,8,4], category:"metalloid", mass:28.085, stableWeight:true, melt:1414, boil:3265, density:2.329, densityUnit:"g/cm³", phase:"Solid", en:1.9, theoretical:false, blurb:"The semiconductor at the heart of every computer chip." },
  P: { z:15, name:"Phosphorus", shells:[2,8,5], category:"nonmetal", mass:30.974, stableWeight:true, melt:44, boil:281, density:1.823, densityUnit:"g/cm³", phase:"Solid", en:2.19, theoretical:false, blurb:"Essential to DNA and bones; white phosphorus glows in the dark." },
  S: { z:16, name:"Sulfur", shells:[2,8,6], category:"nonmetal", mass:32.06, stableWeight:true, melt:115, boil:445, density:2.07, densityUnit:"g/cm³", phase:"Solid", en:2.58, theoretical:false, blurb:"Gives rotten eggs their smell; known historically as brimstone." },
  Cl: { z:17, name:"Chlorine", shells:[2,8,7], category:"halogen", mass:35.45, stableWeight:true, melt:-102, boil:-34, density:3.2, densityUnit:"g/L", phase:"Gas", en:3.16, theoretical:false, blurb:"Toxic yellow-green gas used to disinfect swimming pools." },
  Ar: { z:18, name:"Argon", shells:[2,8,8], category:"noble-gas", mass:39.948, stableWeight:true, melt:-189, boil:-186, density:1.784, densityUnit:"g/L", phase:"Gas", en:null, theoretical:false, blurb:"Inert gas that fills light bulbs to protect the filament." },
  K: { z:19, name:"Potassium", shells:[2,8,8,1], category:"alkali", mass:39.098, stableWeight:true, melt:64, boil:759, density:0.862, densityUnit:"g/cm³", phase:"Solid", en:0.82, theoretical:false, blurb:"Vital nutrient; reacts violently with water, floating and igniting." },
  Ca: { z:20, name:"Calcium", shells:[2,8,8,2], category:"alkaline-earth", mass:40.078, stableWeight:true, melt:842, boil:1484, density:1.55, densityUnit:"g/cm³", phase:"Solid", en:1, theoretical:false, blurb:"Most abundant metal in the body; builds bones and teeth." },
  Sc: { z:21, name:"Scandium", shells:[2,8,9,2], category:"transition", mass:44.956, stableWeight:true, melt:1541, boil:2836, density:2.985, densityUnit:"g/cm³", phase:"Solid", en:1.36, theoretical:false, blurb:"Used in aerospace alloys and high-intensity stadium lighting." },
  Ti: { z:22, name:"Titanium", shells:[2,8,10,2], category:"transition", mass:47.867, stableWeight:true, melt:1668, boil:3287, density:4.506, densityUnit:"g/cm³", phase:"Solid", en:1.54, theoretical:false, blurb:"Strong as steel but much lighter; used in jets and implants." },
  V: { z:23, name:"Vanadium", shells:[2,8,11,2], category:"transition", mass:50.942, stableWeight:true, melt:1910, boil:3407, density:6, densityUnit:"g/cm³", phase:"Solid", en:1.63, theoretical:false, blurb:"Strengthens steel alloys used in industrial tools." },
  Cr: { z:24, name:"Chromium", shells:[2,8,13,1], category:"transition", mass:51.996, stableWeight:true, melt:1907, boil:2671, density:7.19, densityUnit:"g/cm³", phase:"Solid", en:1.66, theoretical:false, blurb:"Gives stainless steel its shine; source of ruby's red color." },
  Mn: { z:25, name:"Manganese", shells:[2,8,13,2], category:"transition", mass:54.938, stableWeight:true, melt:1246, boil:2061, density:7.21, densityUnit:"g/cm³", phase:"Solid", en:1.55, theoretical:false, blurb:"Essential trace nutrient; makes steel resistant to wear." },
  Fe: { z:26, name:"Iron", shells:[2,8,14,2], category:"transition", mass:55.845, stableWeight:true, melt:1538, boil:2861, density:7.874, densityUnit:"g/cm³", phase:"Solid", en:1.83, theoretical:false, blurb:"Carries oxygen in blood; most common element on Earth by mass." },
  Co: { z:27, name:"Cobalt", shells:[2,8,15,2], category:"transition", mass:58.933, stableWeight:true, melt:1495, boil:2927, density:8.9, densityUnit:"g/cm³", phase:"Solid", en:1.88, theoretical:false, blurb:"Used in battery cathodes and deep blue glass pigments." },
  Ni: { z:28, name:"Nickel", shells:[2,8,16,2], category:"transition", mass:58.693, stableWeight:true, melt:1455, boil:2730, density:8.908, densityUnit:"g/cm³", phase:"Solid", en:1.91, theoretical:false, blurb:"Corrosion-resistant metal used in coins and stainless steel." },
  Cu: { z:29, name:"Copper", shells:[2,8,18,1], category:"transition", mass:63.546, stableWeight:true, melt:1085, boil:2562, density:8.96, densityUnit:"g/cm³", phase:"Solid", en:1.9, theoretical:false, blurb:"Excellent conductor used in electrical wiring and plumbing." },
  Zn: { z:30, name:"Zinc", shells:[2,8,18,2], category:"transition", mass:65.382, stableWeight:true, melt:420, boil:907, density:7.14, densityUnit:"g/cm³", phase:"Solid", en:1.65, theoretical:false, blurb:"Coats steel to prevent rust; also vital for immune health." },
  Ga: { z:31, name:"Gallium", shells:[2,8,18,3], category:"post-metal", mass:69.723, stableWeight:true, melt:30, boil:2400, density:5.91, densityUnit:"g/cm³", phase:"Solid", en:1.81, theoretical:false, blurb:"Metal that melts at just below body temperature." },
  Ge: { z:32, name:"Germanium", shells:[2,8,18,4], category:"metalloid", mass:72.631, stableWeight:true, melt:938, boil:2833, density:5.323, densityUnit:"g/cm³", phase:"Solid", en:2.01, theoretical:false, blurb:"A semiconductor used in early transistors and fiber optics." },
  As: { z:33, name:"Arsenic", shells:[2,8,18,5], category:"metalloid", mass:74.922, stableWeight:true, melt:null, boil:615, density:5.727, densityUnit:"g/cm³", phase:"Solid", en:2.18, theoretical:false, blurb:"Notoriously poisonous; historically used in wood preservatives." },
  Se: { z:34, name:"Selenium", shells:[2,8,18,6], category:"nonmetal", mass:78.972, stableWeight:true, melt:221, boil:685, density:4.81, densityUnit:"g/cm³", phase:"Solid", en:2.55, theoretical:false, blurb:"Nutrient used in light sensors and solar cells." },
  Br: { z:35, name:"Bromine", shells:[2,8,18,7], category:"halogen", mass:79.904, stableWeight:true, melt:-7, boil:59, density:3.1028, densityUnit:"g/cm³", phase:"Liquid", en:2.96, theoretical:false, blurb:"One of two liquid elements at room temp; very corrosive." },
  Kr: { z:36, name:"Krypton", shells:[2,8,18,8], category:"noble-gas", mass:83.798, stableWeight:true, melt:-157, boil:-153, density:3.749, densityUnit:"g/L", phase:"Gas", en:3, theoretical:false, blurb:"Used in high-speed photography and specialized lighting." },
  Rb: { z:37, name:"Rubidium", shells:[2,8,18,8,1], category:"alkali", mass:85.468, stableWeight:true, melt:39, boil:688, density:1.532, densityUnit:"g/cm³", phase:"Solid", en:0.82, theoretical:false, blurb:"Soft, reactive alkali metal used in atomic clocks." },
  Sr: { z:38, name:"Strontium", shells:[2,8,18,8,2], category:"alkaline-earth", mass:87.621, stableWeight:true, melt:777, boil:1377, density:2.64, densityUnit:"g/cm³", phase:"Solid", en:0.95, theoretical:false, blurb:"Gives fireworks and flares their brilliant red color." },
  Y: { z:39, name:"Yttrium", shells:[2,8,18,9,2], category:"transition", mass:88.906, stableWeight:true, melt:1526, boil:2930, density:4.472, densityUnit:"g/cm³", phase:"Solid", en:1.22, theoretical:false, blurb:"Used in LED phosphors and high-temp superconductors." },
  Zr: { z:40, name:"Zirconium", shells:[2,8,18,10,2], category:"transition", mass:91.224, stableWeight:true, melt:1855, boil:4377, density:6.52, densityUnit:"g/cm³", phase:"Solid", en:1.33, theoretical:false, blurb:"Clads nuclear fuel rods; highly corrosion-resistant." },
  Nb: { z:41, name:"Niobium", shells:[2,8,18,12,1], category:"transition", mass:92.906, stableWeight:true, melt:2477, boil:4744, density:8.57, densityUnit:"g/cm³", phase:"Solid", en:1.6, theoretical:false, blurb:"Superconductor used in MRI machines and accelerators." },
  Mo: { z:42, name:"Molybdenum", shells:[2,8,18,13,1], category:"transition", mass:95.951, stableWeight:true, melt:2623, boil:4639, density:10.28, densityUnit:"g/cm³", phase:"Solid", en:2.16, theoretical:false, blurb:"Strengthens steel for high-temperature use." },
  Tc: { z:43, name:"Technetium", shells:[2,8,18,13,2], category:"transition", mass:98, stableWeight:false, melt:2157, boil:4265, density:11, densityUnit:"g/cm³", phase:"Solid", en:1.9, theoretical:false, blurb:"Lightest element with no stable isotopes; used in medicine." },
  Ru: { z:44, name:"Ruthenium", shells:[2,8,18,15,1], category:"transition", mass:101.072, stableWeight:true, melt:2334, boil:4150, density:12.45, densityUnit:"g/cm³", phase:"Solid", en:2.2, theoretical:false, blurb:"Rare platinum-group metal used to harden electronics." },
  Rh: { z:45, name:"Rhodium", shells:[2,8,18,16,1], category:"transition", mass:102.906, stableWeight:true, melt:1964, boil:3695, density:12.41, densityUnit:"g/cm³", phase:"Solid", en:2.28, theoretical:false, blurb:"Rare and reflective; used in white gold and catalysts." },
  Pd: { z:46, name:"Palladium", shells:[2,8,18,18], category:"transition", mass:106.421, stableWeight:true, melt:1555, boil:2963, density:12.023, densityUnit:"g/cm³", phase:"Solid", en:2.2, theoretical:false, blurb:"Absorbs hydrogen; vital for catalytic converters." },
  Ag: { z:47, name:"Silver", shells:[2,8,18,18,1], category:"transition", mass:107.868, stableWeight:true, melt:962, boil:2162, density:10.49, densityUnit:"g/cm³", phase:"Solid", en:1.93, theoretical:false, blurb:"The best electrical conductor of any element." },
  Cd: { z:48, name:"Cadmium", shells:[2,8,18,18,2], category:"transition", mass:112.414, stableWeight:true, melt:321, boil:767, density:8.65, densityUnit:"g/cm³", phase:"Solid", en:1.69, theoretical:false, blurb:"Toxic heavy metal once used in batteries and pigments." },
  In: { z:49, name:"Indium", shells:[2,8,18,18,3], category:"post-metal", mass:114.818, stableWeight:true, melt:157, boil:2072, density:7.31, densityUnit:"g/cm³", phase:"Solid", en:1.78, theoretical:false, blurb:"Soft metal used for conductive touchscreen coatings." },
  Sn: { z:50, name:"Tin", shells:[2,8,18,18,4], category:"post-metal", mass:118.711, stableWeight:true, melt:232, boil:2602, density:7.365, densityUnit:"g/cm³", phase:"Solid", en:1.96, theoretical:false, blurb:"Mixed with copper to make bronze; coats food cans." },
  Sb: { z:51, name:"Antimony", shells:[2,8,18,18,5], category:"metalloid", mass:121.76, stableWeight:true, melt:631, boil:1635, density:6.697, densityUnit:"g/cm³", phase:"Solid", en:2.05, theoretical:false, blurb:"Used in flame retardants and lead-acid batteries." },
  Te: { z:52, name:"Tellurium", shells:[2,8,18,18,6], category:"metalloid", mass:127.603, stableWeight:true, melt:450, boil:988, density:6.24, densityUnit:"g/cm³", phase:"Solid", en:2.1, theoretical:false, blurb:"Rare metalloid used in solar panels and steel alloys." },
  I: { z:53, name:"Iodine", shells:[2,8,18,18,7], category:"halogen", mass:126.904, stableWeight:true, melt:114, boil:184, density:4.933, densityUnit:"g/cm³", phase:"Solid", en:2.66, theoretical:false, blurb:"Essential for thyroid health; common antiseptic." },
  Xe: { z:54, name:"Xenon", shells:[2,8,18,18,8], category:"noble-gas", mass:131.294, stableWeight:true, melt:-112, boil:-108, density:5.894, densityUnit:"g/L", phase:"Gas", en:2.6, theoretical:false, blurb:"Used in strobe lights and spacecraft ion thrusters." },
  Cs: { z:55, name:"Cesium", shells:[2,8,18,18,8,1], category:"alkali", mass:132.905, stableWeight:true, melt:29, boil:671, density:1.93, densityUnit:"g/cm³", phase:"Solid", en:0.79, theoretical:false, blurb:"Most reactive stable metal; its transition defines the second." },
  Ba: { z:56, name:"Barium", shells:[2,8,18,18,8,2], category:"alkaline-earth", mass:137.328, stableWeight:true, melt:727, boil:1845, density:3.51, densityUnit:"g/cm³", phase:"Solid", en:0.89, theoretical:false, blurb:"Used in digestive system X-rays (barium meal)." },
  La: { z:57, name:"Lanthanum", shells:[2,8,18,18,9,2], category:"lanthanide", mass:138.905, stableWeight:true, melt:920, boil:3464, density:6.162, densityUnit:"g/cm³", phase:"Solid", en:1.1, theoretical:false, blurb:"Used in camera lenses and hybrid car batteries." },
  Ce: { z:58, name:"Cerium", shells:[2,8,18,19,9,2], category:"lanthanide", mass:140.116, stableWeight:true, melt:795, boil:3443, density:6.77, densityUnit:"g/cm³", phase:"Solid", en:1.12, theoretical:false, blurb:"Most abundant rare-earth metal; used in lighter flints." },
  Pr: { z:59, name:"Praseodymium", shells:[2,8,18,21,8,2], category:"lanthanide", mass:140.908, stableWeight:true, melt:935, boil:3130, density:6.77, densityUnit:"g/cm³", phase:"Solid", en:1.13, theoretical:false, blurb:"Used to color glass yellow-green and in magnets." },
  Nd: { z:60, name:"Neodymium", shells:[2,8,18,22,8,2], category:"lanthanide", mass:144.242, stableWeight:true, melt:1024, boil:3074, density:7.01, densityUnit:"g/cm³", phase:"Solid", en:1.14, theoretical:false, blurb:"Found in high-strength magnets for headphones and drives." },
  Pm: { z:61, name:"Promethium", shells:[2,8,18,23,8,2], category:"lanthanide", mass:145, stableWeight:false, melt:1042, boil:3000, density:7.26, densityUnit:"g/cm³", phase:"Solid", en:1.13, theoretical:false, blurb:"Only radioactive lanthanide; used in nuclear batteries." },
  Sm: { z:62, name:"Samarium", shells:[2,8,18,24,8,2], category:"lanthanide", mass:150.362, stableWeight:true, melt:1072, boil:1900, density:7.52, densityUnit:"g/cm³", phase:"Solid", en:1.17, theoretical:false, blurb:"Used in magnets and for dating old rocks." },
  Eu: { z:63, name:"Europium", shells:[2,8,18,25,8,2], category:"lanthanide", mass:151.964, stableWeight:true, melt:826, boil:1529, density:5.264, densityUnit:"g/cm³", phase:"Solid", en:1.2, theoretical:false, blurb:"Provides red screen phosphors; used in Euro bills." },
  Gd: { z:64, name:"Gadolinium", shells:[2,8,18,25,9,2], category:"lanthanide", mass:157.253, stableWeight:true, melt:1312, boil:3000, density:7.9, densityUnit:"g/cm³", phase:"Solid", en:1.2, theoretical:false, blurb:"Highly magnetic contrast agent for MRI scans." },
  Tb: { z:65, name:"Terbium", shells:[2,8,18,27,8,2], category:"lanthanide", mass:158.925, stableWeight:true, melt:1356, boil:3123, density:8.23, densityUnit:"g/cm³", phase:"Solid", en:1.1, theoretical:false, blurb:"Used in green phosphors for digital displays." },
  Dy: { z:66, name:"Dysprosium", shells:[2,8,18,28,8,2], category:"lanthanide", mass:162.5, stableWeight:true, melt:1407, boil:2567, density:8.54, densityUnit:"g/cm³", phase:"Solid", en:1.22, theoretical:false, blurb:"Added to magnets to survive high heat (EV motors)." },
  Ho: { z:67, name:"Holmium", shells:[2,8,18,29,8,2], category:"lanthanide", mass:164.93, stableWeight:true, melt:1461, boil:2600, density:8.79, densityUnit:"g/cm³", phase:"Solid", en:1.23, theoretical:false, blurb:"Has the highest magnetic strength of any element." },
  Er: { z:68, name:"Erbium", shells:[2,8,18,30,8,2], category:"lanthanide", mass:167.259, stableWeight:true, melt:1529, boil:2868, density:9.066, densityUnit:"g/cm³", phase:"Solid", en:1.24, theoretical:false, blurb:"Amplifies signals in long-distance fiber optics." },
  Tm: { z:69, name:"Thulium", shells:[2,8,18,31,8,2], category:"lanthanide", mass:168.934, stableWeight:true, melt:1545, boil:1950, density:9.32, densityUnit:"g/cm³", phase:"Solid", en:1.25, theoretical:false, blurb:"Rare metal used in portable medical X-rays." },
  Yb: { z:70, name:"Ytterbium", shells:[2,8,18,32,8,2], category:"lanthanide", mass:173.045, stableWeight:true, melt:824, boil:1196, density:6.9, densityUnit:"g/cm³", phase:"Solid", en:1.1, theoretical:false, blurb:"Used in atomic clocks and earthquake stress gauges." },
  Lu: { z:71, name:"Lutetium", shells:[2,8,18,32,9,2], category:"lanthanide", mass:174.967, stableWeight:true, melt:1652, boil:3402, density:9.841, densityUnit:"g/cm³", phase:"Solid", en:1.27, theoretical:false, blurb:"The last lanthanide; used in PET scanners." },
  Hf: { z:72, name:"Hafnium", shells:[2,8,18,32,10,2], category:"transition", mass:178.492, stableWeight:true, melt:2233, boil:4603, density:13.31, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Used in nuclear control rods and microprocessors." },
  Ta: { z:73, name:"Tantalum", shells:[2,8,18,32,11,2], category:"transition", mass:180.948, stableWeight:true, melt:3017, boil:5458, density:16.69, densityUnit:"g/cm³", phase:"Solid", en:1.5, theoretical:false, blurb:"Used in corrosion-resistant smartphone capacitors." },
  W: { z:74, name:"Tungsten", shells:[2,8,18,32,12,2], category:"transition", mass:183.841, stableWeight:true, melt:3422, boil:5930, density:19.25, densityUnit:"g/cm³", phase:"Solid", en:2.36, theoretical:false, blurb:"Metal with the highest melting point; lightbulb filament." },
  Re: { z:75, name:"Rhenium", shells:[2,8,18,32,13,2], category:"transition", mass:186.207, stableWeight:true, melt:3186, boil:5596, density:21.02, densityUnit:"g/cm³", phase:"Solid", en:1.9, theoretical:false, blurb:"Used in superalloys for jet engines." },
  Os: { z:76, name:"Osmium", shells:[2,8,18,32,14,2], category:"transition", mass:190.233, stableWeight:true, melt:3033, boil:5012, density:22.59, densityUnit:"g/cm³", phase:"Solid", en:2.2, theoretical:false, blurb:"Densest naturally occurring element." },
  Ir: { z:77, name:"Iridium", shells:[2,8,18,32,15,2], category:"transition", mass:192.217, stableWeight:true, melt:2446, boil:4130, density:22.56, densityUnit:"g/cm³", phase:"Solid", en:2.2, theoretical:false, blurb:"Most corrosion-resistant metal; marks dinosaur extinction." },
  Pt: { z:78, name:"Platinum", shells:[2,8,18,32,17,1], category:"transition", mass:195.085, stableWeight:true, melt:1768, boil:3825, density:21.45, densityUnit:"g/cm³", phase:"Solid", en:2.28, theoretical:false, blurb:"Precious metal used in jewelry and catalytic converters." },
  Au: { z:79, name:"Gold", shells:[2,8,18,32,18,1], category:"transition", mass:196.967, stableWeight:true, melt:1064, boil:2970, density:19.3, densityUnit:"g/cm³", phase:"Solid", en:2.54, theoretical:false, blurb:"Precious noble metal that never tarnishes or corrodes." },
  Hg: { z:80, name:"Mercury", shells:[2,8,18,32,18,2], category:"transition", mass:200.592, stableWeight:true, melt:-39, boil:357, density:13.534, densityUnit:"g/cm³", phase:"Liquid", en:2, theoretical:false, blurb:"The only metal that is liquid at room temperature." },
  Tl: { z:81, name:"Thallium", shells:[2,8,18,32,18,3], category:"post-metal", mass:204.38, stableWeight:true, melt:304, boil:1473, density:11.85, densityUnit:"g/cm³", phase:"Solid", en:1.62, theoretical:false, blurb:"Highly toxic metal historically used as rat poison." },
  Pb: { z:82, name:"Lead", shells:[2,8,18,32,18,4], category:"post-metal", mass:207.21, stableWeight:true, melt:327, boil:1749, density:11.34, densityUnit:"g/cm³", phase:"Solid", en:1.87, theoretical:false, blurb:"Dense metal once common in pipes and paint." },
  Bi: { z:83, name:"Bismuth", shells:[2,8,18,32,18,5], category:"post-metal", mass:208.98, stableWeight:true, melt:272, boil:1564, density:9.78, densityUnit:"g/cm³", phase:"Solid", en:2.02, theoretical:false, blurb:"Non-toxic heavy metal used in stomach medicines." },
  Po: { z:84, name:"Polonium", shells:[2,8,18,32,18,6], category:"post-metal", mass:209, stableWeight:false, melt:254, boil:962, density:9.196, densityUnit:"g/cm³", phase:"Solid", en:2, theoretical:false, blurb:"Highly radioactive; discovered by Marie Curie." },
  At: { z:85, name:"Astatine", shells:[2,8,18,32,18,7], category:"halogen", mass:210, stableWeight:false, melt:302, boil:337, density:6.35, densityUnit:"g/cm³", phase:"Solid", en:2.2, theoretical:false, blurb:"Rarest natural element; less than 30g exists on Earth." },
  Rn: { z:86, name:"Radon", shells:[2,8,18,32,18,8], category:"noble-gas", mass:222, stableWeight:false, melt:-71, boil:-62, density:9.73, densityUnit:"g/L", phase:"Gas", en:2.2, theoretical:false, blurb:"Radioactive gas that seeps from rock; causes lung cancer." },
  Fr: { z:87, name:"Francium", shells:[2,8,18,32,18,8,1], category:"alkali", mass:223, stableWeight:false, melt:27, boil:677, density:1.87, densityUnit:"g/cm³", phase:"Solid", en:0.79, theoretical:false, blurb:"Extremely rare and highly unstable alkali metal." },
  Ra: { z:88, name:"Radium", shells:[2,8,18,32,18,8,2], category:"alkaline-earth", mass:226, stableWeight:false, melt:960, boil:1737, density:5.5, densityUnit:"g/cm³", phase:"Solid", en:0.9, theoretical:false, blurb:"Radioactive element once used in glowing watch hands." },
  Ac: { z:89, name:"Actinium", shells:[2,8,18,32,18,9,2], category:"actinide", mass:227, stableWeight:false, melt:1227, boil:3227, density:10, densityUnit:"g/cm³", phase:"Solid", en:1.1, theoretical:false, blurb:"Glows blue in the dark due to high radioactivity." },
  Th: { z:90, name:"Thorium", shells:[2,8,18,32,18,10,2], category:"actinide", mass:232.038, stableWeight:true, melt:1750, boil:4788, density:11.724, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"A safer nuclear fuel source for next-gen reactors." },
  Pa: { z:91, name:"Protactinium", shells:[2,8,18,32,20,9,2], category:"actinide", mass:231.036, stableWeight:true, melt:1568, boil:4027, density:15.37, densityUnit:"g/cm³", phase:"Solid", en:1.5, theoretical:false, blurb:"Extremely rare and toxic radioactive metal." },
  U: { z:92, name:"Uranium", shells:[2,8,18,32,21,9,2], category:"actinide", mass:238.029, stableWeight:true, melt:1132, boil:4131, density:19.1, densityUnit:"g/cm³", phase:"Solid", en:1.38, theoretical:false, blurb:"Heaviest natural element used for nuclear power." },
  Np: { z:93, name:"Neptunium", shells:[2,8,18,32,22,9,2], category:"actinide", mass:237, stableWeight:false, melt:639, boil:4174, density:20.45, densityUnit:"g/cm³", phase:"Solid", en:1.36, theoretical:false, blurb:"First synthetic transuranic element ever made." },
  Pu: { z:94, name:"Plutonium", shells:[2,8,18,32,24,8,2], category:"actinide", mass:244, stableWeight:false, melt:639, boil:3232, density:19.816, densityUnit:"g/cm³", phase:"Solid", en:1.28, theoretical:false, blurb:"Used in nuclear weapons and space probe power sources." },
  Am: { z:95, name:"Americium", shells:[2,8,18,32,25,8,2], category:"actinide", mass:243, stableWeight:false, melt:1176, boil:2607, density:12, densityUnit:"g/cm³", phase:"Solid", en:1.13, theoretical:false, blurb:"The element found in household smoke detectors." },
  Cm: { z:96, name:"Curium", shells:[2,8,18,32,25,9,2], category:"actinide", mass:247, stableWeight:false, melt:1340, boil:3110, density:13.51, densityUnit:"g/cm³", phase:"Solid", en:1.28, theoretical:false, blurb:"Named after the Curies; powers Mars rover tools." },
  Bk: { z:97, name:"Berkelium", shells:[2,8,18,32,27,8,2], category:"actinide", mass:247, stableWeight:false, melt:986, boil:2627, density:14.78, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Synthesized at Berkeley; used for research only." },
  Cf: { z:98, name:"Californium", shells:[2,8,18,32,28,8,2], category:"actinide", mass:251, stableWeight:false, melt:900, boil:1470, density:15.1, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Strong neutron source used to scan cargo containers." },
  Es: { z:99, name:"Einsteinium", shells:[2,8,18,32,29,8,2], category:"actinide", mass:252, stableWeight:false, melt:860, boil:996, density:8.84, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Discovered in hydrogen bomb test debris; named after Einstein." },
  Fm: { z:100, name:"Fermium", shells:[2,8,18,32,30,8,2], category:"actinide", mass:257, stableWeight:false, melt:1527, boil:null, density:null, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Heaviest element made by neutron bombardment." },
  Md: { z:101, name:"Mendelevium", shells:[2,8,18,32,31,8,2], category:"actinide", mass:258, stableWeight:false, melt:827, boil:null, density:null, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Named after the creator of the table, Mendeleev." },
  No: { z:102, name:"Nobelium", shells:[2,8,18,32,32,8,2], category:"actinide", mass:259, stableWeight:false, melt:827, boil:null, density:null, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"Named after Alfred Nobel." },
  Lr: { z:103, name:"Lawrencium", shells:[2,8,18,32,32,8,3], category:"actinide", mass:266, stableWeight:false, melt:1627, boil:null, density:null, densityUnit:"g/cm³", phase:"Solid", en:1.3, theoretical:false, blurb:"The last member of the actinide series." },
  Rf: { z:104, name:"Rutherfordium", shells:[2,8,18,32,32,10,2], category:"transition", mass:267, stableWeight:false, melt:2127, boil:5527, density:23.2, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"The first superheavy element." },
  Db: { z:105, name:"Dubnium", shells:[2,8,18,32,32,11,2], category:"transition", mass:268, stableWeight:false, melt:null, boil:null, density:29.3, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after Dubna, Russia." },
  Sg: { z:106, name:"Seaborgium", shells:[2,8,18,32,32,12,2], category:"transition", mass:269, stableWeight:false, melt:null, boil:null, density:35, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after Glenn Seaborg." },
  Bh: { z:107, name:"Bohrium", shells:[2,8,18,32,32,13,2], category:"transition", mass:270, stableWeight:false, melt:null, boil:null, density:37.1, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after physicist Niels Bohr." },
  Hs: { z:108, name:"Hassium", shells:[2,8,18,32,32,14,2], category:"transition", mass:269, stableWeight:false, melt:-147, boil:null, density:40.7, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after Hesse, Germany." },
  Mt: { z:109, name:"Meitnerium", shells:[2,8,18,32,32,15,2], category:"transition", mass:278, stableWeight:false, melt:null, boil:null, density:37.4, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after Lise Meitner." },
  Ds: { z:110, name:"Darmstadtium", shells:[2,8,18,32,32,16,2], category:"transition", mass:281, stableWeight:false, melt:null, boil:null, density:34.8, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after Darmstadt, Germany." },
  Rg: { z:111, name:"Roentgenium", shells:[2,8,18,32,32,17,2], category:"transition", mass:282, stableWeight:false, melt:null, boil:null, density:28.7, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after the discoverer of X-rays." },
  Cn: { z:112, name:"Copernicium", shells:[2,8,18,32,32,18,2], category:"transition", mass:285, stableWeight:false, melt:null, boil:3297, density:14.0, densityUnit:"g/cm³", phase:"Liquid", en:null, theoretical:true, blurb:"Named after Copernicus; predicted to be a volatile liquid." },
  Nh: { z:113, name:"Nihonium", shells:[2,8,18,32,32,18,3], category:"transition", mass:286, stableWeight:false, melt:427, boil:1157, density:16, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"First discovered in Asia (Japan)." },
  Fl: { z:114, name:"Flerovium", shells:[2,8,18,32,32,18,4], category:"post-metal", mass:289, stableWeight:false, melt:67, boil:147, density:14, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Synthetic element discovered in Russia." },
  Mc: { z:115, name:"Moscovium", shells:[2,8,18,32,32,18,5], category:"post-metal", mass:289, stableWeight:false, melt:397, boil:1127, density:13.5, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after the Moscow region." },
  Lv: { z:116, name:"Livermorium", shells:[2,8,18,32,32,18,6], category:"post-metal", mass:293, stableWeight:false, melt:436, boil:812, density:12.9, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after Lawrence Livermore Laboratory." },
  Ts: { z:117, name:"Tennessine", shells:[2,8,18,32,32,18,7], category:"halogen", mass:294, stableWeight:false, melt:450, boil:610, density:7.17, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"Named after the state of Tennessee." },
  Og: { z:118, name:"Oganesson", shells:[2,8,18,32,32,18,8], category:"noble-gas", mass:294, stableWeight:false, melt:null, boil:77, density:4.95, densityUnit:"g/cm³", phase:"Solid", en:null, theoretical:true, blurb:"The final element of the Periodic Table." },
};

// FULL COLOR PALETTE (Restored missing colors like Fe, Ag, Si, etc.)
const ATOM_COLOR = {
  H: 0xf2f0ea, C: 0x333333, N: 0x3b6fd9, O: 0xe0483e,
  Na: 0x8a5fd9, Cl: 0x4fbf6b, S: 0xe8c93a, F: 0x90e050,
  Mg: 0x8aff00, Ca: 0x3dff00, K: 0x8f40d4, P: 0xff8000,
  Si: 0xaaaaaa, Al: 0x999999, Fe: 0xdd7733, Ag: 0xc0c0c0,
  Mn: 0x9c7ac7, B: 0xffaa77, default: 0x9a94b3,
};

// RADIUS DEFINITIONS (Restored for new elements)
const ATOM_RADIUS = {
  H: 0.32, C: 0.5, N: 0.48, O: 0.48, Na: 0.6, Cl: 0.58, S: 0.55,
  F: 0.42, Mg: 0.62, Ca: 0.68, K: 0.72, P: 0.55, Si: 0.6,
  Al: 0.65, Fe: 0.7, Ag: 0.7, Mn: 0.65, B: 0.5, default: 0.5,
};

// CATEGORY METADATA
const CATEGORY_META = {
  "nonmetal":        { label: "Nonmetal",               color: "#c9c3e0" },
  "noble-gas":        { label: "Noble Gas",              color: "#7fe8ff" },
  "alkali":           { label: "Alkali Metal",           color: "#ffb454" },
  "alkaline-earth":   { label: "Alkaline Earth Metal",   color: "#ffcf8a" },
  "metalloid":        { label: "Metalloid",              color: "#5ce1c9" },
  "halogen":          { label: "Halogen",                color: "#ff6fae" },
  "post-metal":       { label: "Post-transition Metal",  color: "#b39ddb" },
  "transition":       { label: "Transition Metal",       color: "#7fd9ff" },
  "lanthanide":       { label: "Lanthanide",             color: "#e8c93a" },
  "actinide":         { label: "Actinide",                color: "#ff7043" },
};

// FULL MOLECULE BLURBS
const MOLECULE_BLURBS = {
  H2O: "Water: The universal solvent essential for all life.",
  CO2: "Carbon Dioxide: A greenhouse gas and byproduct of respiration.",
  CH4: "Methane: The primary component of natural gas.",
  NH3: "Ammonia: Pungent gas used in fertilizer production.",
  O2: "Oxygen Gas: The gas aerobic organisms breathe to stay alive.",
  N2: "Nitrogen Gas: Inert gas making up 78% of the atmosphere.",
  NACL: "Sodium Chloride: Ordinary table salt.",
  CO: "Carbon Monoxide: Poisonous gas from incomplete combustion.",
  HCL: "Hydrochloric Acid: Strong acid found in stomach juices.",
  HF: "Hydrogen Fluoride: Dangerous acid used to etch glass.",
  O3: "Ozone: Atmospheric shield against UV radiation.",
  H2S: "Hydrogen Sulfide: Toxic gas with a rotten egg smell.",
  SO2: "Sulfur Dioxide: Contributes to acid rain formation.",
  NO2: "Nitrogen Dioxide: Red-brown air pollutant from engines.",
  N2O: "Nitrous Oxide: Laughing gas; used in dentistry.",
  SO3: "Sulfur Trioxide: Industrial precursor to sulfuric acid.",
  H2O2: "Hydrogen Peroxide: Common disinfectant and oxidizer.",
  C2H2: "Acetylene: Used in high-heat welding torches.",
  C2H4: "Ethylene: Plant hormone; used to make plastic.",
  C2H6: "Ethane: Hydrocarbon found in natural gas.",
  C3H8: "Propane: Common fuel for heating and cooking.",
  CH3OH: "Methanol: Wood alcohol; toxic industrial solvent.",
  C2H5OH: "Ethanol: The alcohol found in beer and wine.",
  CH3COOH: "Acetic Acid: The main component of vinegar.",
  C6H6: "Benzene: Industrial chemical and carcinogen.",
  MGO: "Magnesium Oxide: Used in fireproofing and medicine.",
  KCL: "Potassium Chloride: Common fertilizer and salt substitute.",
  CAO: "Quicklime: Used in steelmaking and water treatment.",
  C6H12O6: "Glucose: Simple sugar; primary energy source for cells.",
  C8H10N4O2: "Caffeine: Stimulant found in coffee and tea.",
  NAHCO3: "Baking Soda: Leavening agent and household cleaner.",
  CACO3: "Calcium Carbonate: Main component of limestone and shells.",
  C3H6O: "Acetone: Solvent used in nail polish remover.",
  H2SO4: "Sulfuric Acid: Highly corrosive industrial acid.",
  H3PO4: "Phosphoric Acid: Used in fertilizers and soft drinks.",
  HNO3: "Nitric Acid: Used in manufacturing explosives.",
  CHCL3: "Chloroform: Anesthetic and industrial solvent.",
  CCL4: "Carbon Tetrachloride: Formerly used in dry cleaning.",
  SIO2: "Silicon Dioxide: Found in sand and glass.",
  AL2O3: "Alumina: Used in ceramics and aluminum production.",
  FE2O3: "Hematite: Main ore of iron; common rust.",
  C2H6O2: "Ethylene Glycol: Automotive antifreeze.",
  C3H8O3: "Glycerin: Used in skincare and food products.",
  CH4N2O: "Urea: Important fertilizer and metabolic waste.",
  H3BO3: "Boric Acid: Mild antiseptic and insecticide.",
  AGCL: "Silver Chloride: Light-sensitive; used in film.",
  KMNO4: "Potassium Permanganate: Water treatment oxidizer.",
  NA2CO3: "Washing Soda: Used to soften water and make glass.",
  MGCL2: "Magnesium Chloride: Used for road de-icing.",
  C9H8O4: "Aspirin: Common painkiller and fever reducer.",
};

// EXPANDED MOLECULES (Fixed geometry for visibility)
const MOLECULES = {
  H2O: { name: "Water", formula: "H₂O", atoms: [{ el: "O", pos: [0, 0, 0] }, { el: "H", pos: [0.76, 0.59, 0] }, { el: "H", pos: [-0.76, 0.59, 0] }], bonds: [[0,1],[0,2]] },
  CO2: { name: "Carbon dioxide", formula: "CO₂", atoms: [{ el: "C", pos: [0,0,0] }, { el: "O", pos: [1.16,0,0] }, { el: "O", pos: [-1.16,0,0] }], bonds: [[0,1],[0,2]] },
  CH4: { name: "Methane", formula: "CH₄", atoms: [{ el: "C", pos: [0,0,0] }, { el: "H", pos: [0.63,0.63,0.63] }, { el: "H", pos: [-0.63,-0.63,0.63] }, { el: "H", pos: [-0.63,0.63,-0.63] }, { el: "H", pos: [0.63,-0.63,-0.63] }], bonds: [[0,1],[0,2],[0,3],[0,4]] },
  NH3: { name: "Ammonia", formula: "NH₃", atoms: [{ el: "N", pos: [0,0.2,0] }, { el: "H", pos: [0.94,-0.3,0] }, { el: "H", pos: [-0.47,-0.3,0.82] }, { el: "H", pos: [-0.47,-0.3,-0.82] }], bonds: [[0,1],[0,2],[0,3]] },
  O2: { name: "Oxygen gas", formula: "O₂", atoms: [{ el: "O", pos: [0.6,0,0] }, { el: "O", pos: [-0.6,0,0] }], bonds: [[0,1]] },
  N2: { name: "Nitrogen gas", formula: "N₂", atoms: [{ el: "N", pos: [0.55,0,0] }, { el: "N", pos: [-0.55,0,0] }], bonds: [[0,1]] },
  NACL: { name: "Sodium chloride", formula: "NaCl", atoms: [{ el: "Na", pos: [0.7,0,0] }, { el: "Cl", pos: [-0.7,0,0] }], bonds: [[0,1]] },
  CO: { name: "Carbon monoxide", formula: "CO", atoms: [{ el: "C", pos: [0.5,0,0] }, { el: "O", pos: [-0.5,0,0] }], bonds: [[0,1]] },
  HCL: { name: "Hydrogen chloride", formula: "HCl", atoms: [{ el: "H", pos: [0.6,0,0] }, { el: "Cl", pos: [-0.6,0,0] }], bonds: [[0,1]] },
  HF: { name: "Hydrogen fluoride", formula: "HF", atoms: [{ el: "H", pos: [0.4,0,0] }, { el: "F", pos: [-0.4,0,0] }], bonds: [[0,1]] },
  O3: { name: "Ozone", formula: "O₃", atoms: [{ el: "O", pos: [0,0,0] }, { el: "O", pos: [1.1,0.6,0] }, { el: "O", pos: [-1.1,0.6,0] }], bonds: [[0,1],[0,2]] },
  H2S: { name: "Hydrogen sulfide", formula: "H₂S", atoms: [{ el: "S", pos: [0,0,0] }, { el: "H", pos: [0.9,0.9,0] }, { el: "H", pos: [-0.9,0.9,0] }], bonds: [[0,1],[0,2]] },
  SO2: { name: "Sulfur dioxide", formula: "SO₂", atoms: [{ el: "S", pos: [0,0,0] }, { el: "O", pos: [1.2,0.7,0] }, { el: "O", pos: [-1.2,0.7,0] }], bonds: [[0,1],[0,2]] },
  NO2: { name: "Nitrogen dioxide", formula: "NO₂", atoms: [{ el: "N", pos: [0,0,0] }, { el: "O", pos: [1.1,0.4,0] }, { el: "O", pos: [-1.1,0.4,0] }], bonds: [[0,1],[0,2]] },
  N2O: { name: "Nitrous oxide", formula: "N₂O", atoms: [{ el: "N", pos: [0,0,0] }, { el: "N", pos: [1.1,0,0] }, { el: "O", pos: [-1.2,0,0] }], bonds: [[0,1],[0,2]] },
  SO3: { name: "Sulfur trioxide", formula: "SO₃", atoms: [{ el: "S", pos: [0,0,0] }, { el: "O", pos: [0,1.4,0] }, { el: "O", pos: [-1.2,-0.7,0] }, { el: "O", pos: [1.2,-0.7,0] }], bonds: [[0,1],[0,2],[0,3]] },
  H2O2: { name: "Hydrogen peroxide", formula: "H₂O₂", atoms: [{ el: "O", pos: [0.7,0,0] }, { el: "O", pos: [-0.7,0,0] }, { el: "H", pos: [0.8,0.6,0.6] }], bonds: [[0,2]] },
  C2H2: { name: "Acetylene", formula: "C₂H₂", atoms: [{ el: "C", pos: [0.6,0,0] }, { el: "C", pos: [-0.6,0,0] }, { el: "H", pos: [1.6,0,0] }, { el: "H", pos: [-1.6,0,0] }], bonds: [[0,1],[0,2],[1,3]] },
  C2H4: { name: "Ethylene", formula: "C₂H₄", atoms: [{ el: "C", pos: [0.6,0,0] }, { el: "C", pos: [-0.6,0,0] }, { el: "H", pos: [1.2,0.9,0] }], bonds: [[0,1],[0,2]] },
  C2H6: { name: "Ethane", formula: "C₂H₆", atoms: [{ el: "C", pos: [0.7,0,0] }, { el: "C", pos: [-0.7,0,0] }], bonds: [[0,1]] },
  C3H8: { name: "Propane", formula: "C₃H₈", atoms: [{ el: "C", pos: [0,0,0] }, { el: "C", pos: [1.2,0,0] }, { el: "C", pos: [-1.2,0,0] }], bonds: [[0,1],[0,2]] },
  CH3OH: { name: "Methanol", formula: "CH₃OH", atoms: [{ el: "C", pos: [0,0,0] }, { el: "O", pos: [1.1,0,0] }, { el: "H", pos: [-0.6,0.6,0] }], bonds: [[0,1],[0,2]] },
  C2H5OH: { name: "Ethanol", formula: "C₂H₅OH", atoms: [{ el: "C", pos: [0.7,0,0] }, { el: "C", pos: [-0.7,0,0] }, { el: "O", pos: [1.5,0.5,0] }], bonds: [[0,1],[0,2]] },
  CH3COOH: { name: "Acetic acid", formula: "CH₃COOH", atoms: [{ el: "C", pos: [0,0,0] }, { el: "C", pos: [1,0.5,0] }, { el: "O", pos: [0.5,1.2,1] }], bonds: [[0,1],[1,2]] },
  C6H6: { name: "Benzene", formula: "C₆H₆", atoms: [{ el: "C", pos: [1.4,0,0] }, { el: "C", pos: [0.7,1.2,0] }, { el: "C", pos: [-0.7,1.2,0] }, { el: "C", pos: [-1.4,0,0] }, { el: "C", pos: [-0.7,-1.2,0] }, { el: "C", pos: [0.7,-1.2,0] }], bonds: [[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]] },
  MGO: { name: "Magnesium oxide", formula: "MgO", atoms: [{ el: "Mg", pos: [0.6,0,0] }, { el: "O", pos: [-0.6,0,0] }], bonds: [[0,1]] },
  KCL: { name: "Potassium chloride", formula: "KCl", atoms: [{ el: "K", pos: [0.8,0,0] }, { el: "Cl", pos: [-0.8,0,0] }], bonds: [[0,1]] },
  CAO: { name: "Calcium oxide", formula: "CaO", atoms: [{ el: "Ca", pos: [0.7,0,0] }, { el: "O", pos: [-0.7,0,0] }], bonds: [[0,1]] },
  C3H6O: { name: "Acetone", formula: "C₃H₆O", atoms: [{ el: "C", pos: [0,0,0] }, { el: "O", pos: [0,1.2,0] }, { el: "C", pos: [1,-0.5,0] }, { el: "C", pos: [-1,-0.5,0] }], bonds: [[0,1],[0,2],[0,3]] },
  C6H12O6: { name: "Glucose", formula: "C₆H₁₂O₆", atoms: [{ el: "C", pos: [0,0,0] }, { el: "C", pos: [1,0,0] }, { el: "O", pos: [1.5,0.8,0] }], bonds: [[0,1],[1,2]] },
  C8H10N4O2: { name: "Caffeine", formula: "C₈H₁₀N₄O₂", atoms: [{ el: "C", pos: [0,0,0] }, { el: "N", pos: [1,0,0] }, { el: "C", pos: [1.5,0.8,0] }], bonds: [[0,1],[1,2]] },
  NAHCO3: { name: "Baking soda", formula: "NaHCO₃", atoms: [{ el: "Na", pos: [0,1.2,0] }, { el: "C", pos: [0,0,0] }, { el: "O", pos: [1,0,0] }], bonds: [[1,2]] },
  CACO3: { name: "Calcium carbonate", formula: "CaCO₃", atoms: [{ el: "Ca", pos: [0,1.2,0] }, { el: "C", pos: [0,0,0] }, { el: "O", pos: [1,0,0] }], bonds: [[1,2]] },
  H2SO4: { name: "Sulfuric acid", formula: "H₂SO₄", atoms: [{ el: "S", pos: [0,0,0] }, { el: "O", pos: [1,1,1] }, { el: "O", pos: [-1,-1,1] }], bonds: [[0,1],[0,2]] },
  H3PO4: { name: "Phosphoric acid", formula: "H₃PO₄", atoms: [{ el: "P", pos: [0,0,0] }, { el: "O", pos: [1,1,1] }], bonds: [[0,1]] },
  HNO3: { name: "Nitric acid", formula: "HNO₃", atoms: [{ el: "N", pos: [0,0,0] }, { el: "O", pos: [1,1,1] }], bonds: [[0,1]] },
  CHCL3: { name: "Chloroform", formula: "CHCl₃", atoms: [{ el: "C", pos: [0,0,0] }, { el: "Cl", pos: [1.5,0,0] }, { el: "Cl", pos: [-1,1,0] }], bonds: [[0,1],[0,2]] },
  CCL4: { name: "Carbon tetrachloride", formula: "CCl₄", atoms: [{ el: "C", pos: [0,0,0] }, { el: "Cl", pos: [1.5,0,0] }, { el: "Cl", pos: [-1,1,0] }], bonds: [[0,1],[0,2]] },
  SIO2: { name: "Silicon dioxide", formula: "SiO₂", atoms: [{ el: "Si", pos: [0,0,0] }, { el: "O", pos: [1.5,0,0] }, { el: "O", pos: [-1.5,0,0] }], bonds: [[0,1],[0,2]] },
  AL2O3: { name: "Aluminum oxide", formula: "Al₂O₃", atoms: [{ el: "Al", pos: [1,0,0] }, { el: "O", pos: [-1,0,0] }], bonds: [[0,1]] },
  FE2O3: { name: "Iron(III) oxide", formula: "Fe₂O₃", atoms: [{ el: "Fe", pos: [1,0,0] }, { el: "O", pos: [-1,0,0] }], bonds: [[0,1]] },
  C2H6O2: { name: "Ethylene glycol", formula: "C₂H₆O₂", atoms: [{ el: "C", pos: [0,0,0] }, { el: "O", pos: [1,1,0] }], bonds: [[0,1]] },
  C3H8O3: { name: "Glycerol", formula: "C₃H₈O₃", atoms: [{ el: "C", pos: [0,0,0] }, { el: "O", pos: [1,1,0] }], bonds: [[0,1]] },
  CH4N2O: { name: "Urea", formula: "CH₄N₂O", atoms: [{ el: "C", pos: [0,0,0] }, { el: "N", pos: [1,1,0] }], bonds: [[0,1]] },
  H3BO3: { name: "Boric acid", formula: "H₃BO₃", atoms: [{ el: "B", pos: [0,0,0] }, { el: "O", pos: [1,1,0] }], bonds: [[0,1]] },
  AGCL: { name: "Silver chloride", formula: "AgCl", atoms: [{ el: "Ag", pos: [0.8,0,0] }, { el: "Cl", pos: [-0.8,0,0] }], bonds: [[0,1]] },
  KMNO4: { name: "Potassium permanganate", formula: "KMnO₄", atoms: [{ el: "Mn", pos: [0,0,0] }, { el: "K", pos: [1.5,1.5,0] }, { el: "O", pos: [-1,0,0] }], bonds: [[0,2]] },
  NA2CO3: { name: "Sodium carbonate", formula: "Na₂CO₃", atoms: [{ el: "C", pos: [0,0,0] }, { el: "Na", pos: [1.5,0,0] }, { el: "O", pos: [-1,0,0] }], bonds: [[0,2]] },
  MGCL2: { name: "Magnesium chloride", formula: "MgCl₂", atoms: [{ el: "Mg", pos: [0,0,0] }, { el: "Cl", pos: [1.5,0,0] }, { el: "Cl", pos: [-1.5,0,0] }], bonds: [[0,1],[0,2]] },
  C9H8O4: { name: "Aspirin", formula: "C₉H₈O₄", atoms: [{ el: "C", pos: [0,0,0] }, { el: "O", pos: [1,1,0] }], bonds: [[0,1]] },
};

const ALLOYS = {
  STEEL: { name: "Steel", composition: "Iron + Carbon", category: "Ferrous Alloy", blurb: "Commonly used in construction; strong and recyclable." },
  BRASS: { name: "Brass", composition: "Copper + Zinc", category: "Copper Alloy", blurb: "Valued for its gold-like color and acoustic properties." },
  BRONZE: { name: "Bronze", composition: "Copper + Tin", category: "Copper Alloy", blurb: "Harder than copper; historically revolutionized tool making." },
  STAINLESS_STEEL: { name: "Stainless Steel", composition: "Iron + Chromium + Nickel", category: "Ferrous Alloy", blurb: "Resists rust; ideal for cutlery and medical tools." },
  STERLING_SILVER: { name: "Sterling Silver", composition: "Silver (92.5%) + Copper", category: "Silver Alloy", blurb: "The standard for high-quality silver jewelry." },
  GOLD_14K: { name: "14k Gold", composition: "Gold + Silver/Copper", category: "Gold Alloy", blurb: "Standard alloy for durable gold jewelry." },
  NITINOL: { name: "Nitinol", composition: "Nickel + Titanium", category: "Shape-Memory Alloy", blurb: "Can return to its original shape when heated." },
  MAGNALIUM: { name: "Magnalium", composition: "Aluminium + Magnesium", category: "Lightweight Alloy", blurb: "Used in aircraft and high-end engineering." },
};

function resolveQuery(raw) {
  const q = raw.trim();
  if (!q) return null;
  const key = q.toUpperCase().replace(/\s+/g, "");
  
  if (MOLECULES[key]) return { type: "molecule", key, data: MOLECULES[key] };

  const alloyKey = q.toUpperCase().replace(/\s+/g, "_");
  if (ALLOYS[alloyKey]) return { type: "alloy", key: alloyKey, data: ALLOYS[alloyKey] };

  const byFormula = Object.entries(MOLECULES).find(([, m]) => {
    const cleanFormula = m.formula.replace(/[₀-₉]/g, n => "0123456789"["₀₁₂₃₄₅₆₇₈₉".indexOf(n)]).toUpperCase();
    return cleanFormula === key || m.name.toUpperCase() === q.toUpperCase();
  });
  if (byFormula) return { type: "molecule", key: byFormula[0], data: byFormula[1] };

  const sym = q.charAt(0).toUpperCase() + q.slice(1).toLowerCase();
  if (ELEMENTS[sym]) return { type: "element", key: sym, data: ELEMENTS[sym] };

  const byElName = Object.entries(ELEMENTS).find(([, e]) => e.name.toUpperCase() === q.toUpperCase());
  if (byElName) return { type: "element", key: byElName[0], data: byElName[1] };

  return null;
}
